### ISSUE TITLE
Disable submit button and inputs for read-only portfolios

### ISSUE THREAD

**Issue by spigo900** [spigo900/abet-submission-system#21]
**[FR8]**
**Description:**
As a user, I want read-only course portfolios' pages to make it clear that the portfolio is read-only so that I don't accidentally enter evaluation info into a portfolio I can't actually edit.

Part of the epic in issue #17.

**Priority:** Low
**Effort:** 2
**Acceptance Criteria:**
1. [ ] There should be no submit button on course portfolio pages where the portfolio is read-only.
2. [x] Evaluation information should not be editable on course portfolio pages where the portfolio is read-only.

   (Note that the values could be displayed raw, or in disabled input boxes. It doesn't matter which.)

**Comment by PeterBifone** [comment]
Testing 
1. Seeded the database with 1 active and 1 inactive courses.
2. Navigated to /courses
3. Click edit on the active course
4. Verified that all buttons and fields are enabled 
5. Navigated to /courses
6. Click view on inactive course
7. Verified that all buttons and fields are disabled

For modification to .get:
see Test cases
