### ISSUE TITLE
Create a function to calculate number of blanks we need for the Artifacts given the number of students

### ISSUE THREAD

**Issue by PeterBifone** [spigo900/abet-submission-system#24]
**[FR 14]**
**Description:**
As a professor, I want to know how many students I need to evaluate, so that I do not get fired.

**Priority:** Medium
**Effort:** 1
**Acceptance Criteria:**
1. [x] The function should return the number of students that need to be evaluated.
2. [x] The function should return 10 students or 20% of the number of students (rounded down), whichever is higher, up to a maximum of the class size.

**Comment by spigo900** [comment]
**TODO:** I think I did this incorrectly when I implemented #14.

I think when FR9 refers to the "percent of uploaded student evaluations," it means the evaluations that go in each artifact. That is, for each artifact, the instructor needs to upload evaluations for K students (where K is the number computed by the function described in this issue). So an instructor needs to upload 3*K evaluations in total.

But when I implemented #14, I assumed evaluations worked like this: There are three "evaluations" per SLO, each "evaluation" corresponding to one of the three artifact/SLO pairs. Each "evaluation" consists of a list of "SLO-metric evaluations" (each of which is one of meets, exceeds, etc.) for each student index in the artifact.
