### ISSUE TITLE
Let instructors create new course portfolios

### ISSUE THREAD

**Issue by spigo900** [spigo900/abet-submission-system#7]
**[FR2]**
**Description:**
As an an instructor, I want to be able to start new course portfolios so I can enter evaluations for new courses.

**Priority**: High
**Effort**: 3
**Acceptance Criteria:**
1. [x] When you click on the link to create a new course portfolio, it displays a form to enter the new course portfolio information.
2. [x] The form should include a field for the course number.
3. [x] The form should include a checkbox for each SLO.
4. [x] When you submit the form in (1), it creates the appropriate stuff in the database for a new course portfolio.

**Assigned:** Joe Cecil

**Comment by PeterBifone** [comment]
Add artifacts

**Comment by spigo900** [comment]
Also fix this so it inserts expiration date + read only status

**Comment by spigo900** [comment]
Also, I'm not sure what page it takes you to after you submit the form. It should probably take you to either (1) the `courses` page or (2) the submission page for the first artifact.

**Comment by spigo900** [comment]
Apparently it [already redirects correctly](https://github.com/spigo900/abet-submission-system/blob/e62ed1afd8c74c8b083167f0a3dbd838454d43e8/src/main/routes/course.js#L152) when you submit the form.
